MayOneUS/mayday-2.0-backend

app/models/location.rb
app/models/person.rb
db/migrate/20150224001731_create_people.rb
db/migrate/20150224001912_create_locations.rb
db/schema.rb

Add basic person models

---

app/controllers/v1/legislators_controller.rb
app/models/district.rb
app/models/person.rb
app/views/v1/legislators/index.jbuilder
spec/controllers/v1/legislators_controller_spec.rb
spec/factories.rb

moved logic from view to LegislatorsController

Rep lookup

---

app/controllers/v1/events_controller.rb
config/routes.rb

add events endpoint with dummy response data

Events index

---

app/models/legislator.rb
spec/models/legislator_spec.rb

rename Legislator.find_or_create_by => Legislator.create_or_update

---

README.md
app/controllers/v1/events_controller.rb
app/models/event.rb
app/views/v1/events/_event.jbuilder
app/views/v1/events/index.jbuilder
lib/tasks/seed.rake
spec/controllers/v1/events_controller_spec.rb
spec/factories.rb
spec/models/event_spec.rb

update events controller to display actual events
add events to dummy seed data

add events

---

Gemfile
Gemfile.lock
app/controllers/calls_controller.rb
app/controllers/v1/legislators_controller.rb
app/models/legislator.rb
config/routes.rb
spec/controllers/v1/legislators_controller_spec.rb
spec/models/legislator_spec.rb

This creates and endpoint to use to populate the sidebar on "The Plan" page.

Add targeted legislators endpoint

---

app/models/person.rb
spec/models/person_spec.rb

still need to test Person#legislators (and District#legislators, I guess)

add method Person#constituent_of?(legislator)

---

app/controllers/calls_controller.rb
app/models/ivr/call.rb
app/models/ivr/connection.rb
app/models/person.rb
lib/audio_file_fetcher.rb
spec/controllers/calls_controller_spec.rb
spec/models/ivr/call_spec.rb
spec/models/ivr/connection_spec.rb
spec/models/person_spec.rb

This allows folks to call in to the number.

Mf create calls on fly

---

app/models/person.rb
app/models/zip_code.rb
spec/factories.rb
spec/models/location_spec.rb
spec/models/person_spec.rb

`unconvinced_legislators` was returning ineligible senators
also, there were some tests in location_spec that weren't really testing anything

fix minor bug introduced by last refactor and add test to cover

---

.env.example
Gemfile
Gemfile.lock
Procfile
app/controllers/v1/people_controller.rb
app/jobs/nb_person_push_address_job.rb
app/jobs/nb_person_push_job.rb
app/models/location.rb
app/models/person.rb
config/initializers/active_job.rb
config/initializers/sidekiq.rb
db/migrate/20150307080302_add_name_fields_to_people.rb
db/schema.rb
lib/integration/mobile_commons.rb
lib/integration/nation_builder.rb
spec/controllers/v1/people_controller_spec.rb
spec/jobs/nb_person_push_address_job_spec.rb
spec/jobs/nb_person_push_job_spec.rb
spec/models/legislator_spec.rb
spec/models/location_spec.rb
spec/models/person_spec.rb

People controller now saves to Person model (which pushes to NB)
Added first name and last name to Person model (so people can create accounts some day)
Added tagging capabilities

Save person info to DB before passing to NB

---

app/controllers/v1/nominations_controller.rb
app/jobs/google_forms_submit_job.rb
config/routes.rb
lib/integration/google_forms.rb
spec/controllers/v1/nominations_controller_spec.rb
spec/jobs/google_forms_submit_job_spec.rb
spec/lib/integration/google_forms_spec.rb

maybe a little overbuilt for what we need, but who knows -- maybe we'll want to use Google Forms again someday
submissions get added to this spreadsheet: docs.google.com/spreadsheets/d/1cLnlQRETopQXYvZGPEGTsk51FNFsD_YmyunHHbVmDkg

nominations

---

config/application.rb
spec/lib/external_count_fetcher_spec.rb

this should enable gzip compression. Works on my local machine, anyway
before launch we (I) should also go through index.json legislators view and remove any unnecessary fields

enable deflater

---

app/controllers/v1/blog_posts_controller.rb
lib/blog_fetcher.rb
spec/lib/blog_fetcher_spec.rb

Add a force param to update redis, also removed some strings wrapping
the core json data

BlogPosts:

---

app/controllers/v1/actions_controller.rb
app/models/action.rb
app/models/activity.rb
app/models/person.rb
config/routes.rb
db/migrate/20150415195333_create_activities.rb
db/migrate/20150415195410_create_actions.rb
db/schema.rb
spec/controllers/v1/actions_controller_spec.rb
spec/factories.rb

action endpoint creates action and returns success or error (I will update to return person object)
still need to add uuid to person

add actions, activities, and related endpoint

---

app/controllers/v1/actions_controller.rb
app/models/person.rb
app/views/v1/actions/create.jbuilder
spec/controllers/v1/actions_controller_spec.rb

action controller doesn't have great error messages right now, but I couldn't see a good way to check for valid person, activity, and action without a lot of nested ifs. Can add later if desired

action controller returns person object

---

app/controllers/v1/bills_controller.rb
app/controllers/v1/legislators_controller.rb
app/models/bill.rb
app/models/legislator.rb

still need to add support for `pledged` (any support is considered `cosponsor` right now)

update supporters_map endpoint

---

app/models/legislator.rb
app/models/person.rb
app/views/v1/actions/create.jbuilder
lib/tasks/seed.rake
spec/controllers/v1/actions_controller_spec.rb

oops, forget to switch branches
I didn't add `order` do db yet -- just using `id` for now
To do: maybe break `it "returns person object"` into multiple tests?

add activities array to actions API

---

app/controllers/v1/bills_controller.rb
config/routes.rb
lib/all_supporters.rb

first pass at querying supporter counts by chamber. Needs tests

query AllSupporters by chamber

---

app/controllers/v1/actions_controller.rb
app/models/action.rb
app/models/activity.rb
config/routes.rb
db/migrate/20151015113956_add_activity_type_to_activity.rb
db/migrate/20151015120755_add_donation_amount_to_action.rb
db/schema.rb
spec/controllers/v1/actions_controller_spec.rb
spec/factories.rb
spec/models/action_spec.rb

adds the following:
* can track donation amounts
* add activity_type to trck action types
* can count actions by activity_type, by time range

Add action counting

---

spec/controllers/v1/payments_controller_spec.rb

I thought this made it a little easier to follow what was happening in the spec.  feel free to cherry pick anything you want to update
* remove over abstracted method (and use OpenStruct instead of Struct to help simplify)
* don't use tap to return self when unnecessary (I feel like unless we're acting on self, tap shouldn't be used to to return self at the end of a method. Better to be more explicit).
* use stub method every it can be used
* remove some unused 'person' variables

Stripe: Simpler spec

---

app/controllers/v1/donation_pages_controller.rb
app/models/action.rb
app/models/donation_page.rb
app/models/person.rb
app/views/v1/donation_pages/index.json.jbuilder
app/views/v1/donation_pages/show.json.jbuilder
config/application.rb
config/routes.rb
db/migrate/20160108171513_create_donation_pages.rb
db/migrate/20160108175016_add_donation_page_id_to_actions.rb
db/schema.rb
spec/factories.rb
spec/models/donation_page_spec.rb
spec/rails_helper.rb
spec/requests/v1/donation_pages_spec.rb
spec/support/api_helpers.rb

I think everything is up to spec. Not sure if the controller responses/views are exactly what's wanted, but it's a start.
to do

donation pages

---

.gitignore
Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/v1/actions_controller.rb
app/controllers/v1/base_controller.rb
app/models/action.rb
app/models/activity.rb
app/models/location.rb
app/models/person.rb
app/views/v1/actions/_action.json.jbuilder
app/views/v1/actions/index.json.jbuilder
config/routes.rb
db/migrate/20160206214623_add_donor_strike_fields_to_actions.rb
db/schema.rb
spec/controllers/v1/actions_controller_spec.rb
spec/controllers/v1/people_controller_spec.rb
spec/factories.rb
spec/models/action_spec.rb
spec/models/activity_spec.rb
spec/models/person_spec.rb
spec/requests/v1/actions_spec.rb

does not support `GET /actions` at this point (only `GET /activities/:template_id/actions`)
only returns strike amounts at this point. Can easily update to include donation amounts

ActionsController index action

---

app/services/person_with_remote_fields.rb

PersonWithRemoteFields was ignoring state_abbrev and therefore not updating location if city and state_abbrev were passed in

add state_abbrev to LOCAL_FIELDS in PersonWithRemoteFields

---

app/controllers/v1/actions_controller.rb
app/controllers/v1/base_controller.rb
app/controllers/v1/donations_controller.rb
app/controllers/v1/events_controller.rb
app/controllers/v1/google_forms_controller.rb
app/controllers/v1/people_controller.rb
app/services/person_constructor.rb
spec/controllers/v1/events_controller_spec.rb
spec/controllers/v1/google_forms_controller_spec.rb
spec/controllers/v1/ivr/calls_controller_spec.rb
spec/services/person_constructor_spec.rb

@turino This is what I had a mind when I suggested updating the method.  This is basically your other merge request, but simplifying those class methods.  I'm going to assign to you.  
I also broke out the nationbuilder fix into it's own commit so we could keep those changes a little seperate.  It becomes very helpful in situations like this where we want to revisit how something has been refactored, but not lose other important fixes/changes.

Alternative to class-constructor branch
